[env:esp32dev]

platform = espressif32
board = esp32dev
framework = espidf

lib_deps =
    foxkeys/DHT-ESP-IDF@1.0.7


[env:native]

platform = native

test_build_src = true

build_src_filter =
    +<alarm.cpp>
    +<system_state.cpp>

build_flags =
    -DPIO_UNIT_TEST

test_ignore =
    test_embedded